INSERT INTO EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE, QUANTIDADE_INTEGRANTES, STATUS)
VALUES ('Equipe Norte', 'Rocada Mecanizada', 6, 'ATIVA');

INSERT INTO EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE, QUANTIDADE_INTEGRANTES, STATUS)
VALUES ('Equipe Sul', 'Rocada Manual', 4, 'EM_CAMPO');

INSERT INTO EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE, QUANTIDADE_INTEGRANTES, STATUS)
VALUES ('Equipe Preventiva', 'Pulverizacao', 3, 'ATIVA');

INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, ALTURA_VEGETACAO, TIPO_AMBIENTE, ACESSO_DIFICIL, CODIGO_SENSOR, MONITORADO_IOT)
VALUES (10, 11, 20, 'seco', 'N', NULL, 'N');

INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, ALTURA_VEGETACAO, TIPO_AMBIENTE, ACESSO_DIFICIL, CODIGO_SENSOR, MONITORADO_IOT)
VALUES (12, 13, 45, 'normal', 'N', NULL, 'N');

INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, ALTURA_VEGETACAO, TIPO_AMBIENTE, ACESSO_DIFICIL, CODIGO_SENSOR, MONITORADO_IOT)
VALUES (16, 17, 80, 'umido', 'S', 101, 'S');

INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, ALTURA_VEGETACAO, TIPO_AMBIENTE, ACESSO_DIFICIL, CODIGO_SENSOR, MONITORADO_IOT)
VALUES (18, 19, 75, 'umido', 'N', 102, 'S');

INSERT INTO INTERVENCAO_OPERACIONAL
    (TRECHO_ID, EQUIPE_ID, TIPO_SERVICO, PRIORIDADE, STATUS, DATA_PROGRAMADA, OBSERVACAO)
SELECT t.ID, e.ID, 'Pulverizacao', 'ATENCAO', 'PROGRAMADA', SYSDATE + 2, 'Controle preventivo em vegetacao intermediaria'
FROM TRECHO_RODOVIA t
CROSS JOIN EQUIPE_MANUTENCAO e
WHERE t.KM_INICIAL = 12
  AND e.NOME = 'Equipe Preventiva';

INSERT INTO INTERVENCAO_OPERACIONAL
    (TRECHO_ID, EQUIPE_ID, TIPO_SERVICO, PRIORIDADE, STATUS, DATA_PROGRAMADA, OBSERVACAO)
SELECT t.ID, e.ID, 'Rocada Manual', 'URGENTE', 'PROGRAMADA', SYSDATE + 1, 'Trecho de dificil acesso com crescimento elevado'
FROM TRECHO_RODOVIA t
CROSS JOIN EQUIPE_MANUTENCAO e
WHERE t.KM_INICIAL = 16
  AND e.NOME = 'Equipe Sul';

INSERT INTO INTERVENCAO_OPERACIONAL
    (TRECHO_ID, EQUIPE_ID, TIPO_SERVICO, PRIORIDADE, STATUS, DATA_PROGRAMADA, OBSERVACAO)
SELECT t.ID, e.ID, 'Rocada Mecanizada', 'CRITICO', 'PROGRAMADA', SYSDATE + 3, 'Altura critica com acesso para equipamento'
FROM TRECHO_RODOVIA t
CROSS JOIN EQUIPE_MANUTENCAO e
WHERE t.KM_INICIAL = 18
  AND e.NOME = 'Equipe Norte';

INSERT INTO RELATORIO_PRIORIDADE (QT_URGENTE, QT_CRITICO, QT_ATENCAO, QT_NORMAL, RESUMO)
VALUES (1, 1, 1, 1, 'Carga inicial para teste do historico de relatorios.');

COMMIT;
